# Generated by Django 5.0.4 on 2024-04-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_rename_date_of_birth_resumedata_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
    ]
